// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/courses/courses.proto

/*
Package courses is a generated protocol buffer package.

It is generated from these files:
	proto/courses/courses.proto

It has these top-level messages:
	Course
	FilterSet
	UpsertCoursesRequest
	GetCoursesByFiltersRequest
	GetCoursesByFiltersResponse
	DeleteCoursesByFiltersRequest
	DeleteCoursesByFiltersResponse
*/
package courses

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import mysql "github.com/jianhan/course-management-service/proto/mysql"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Course defines data structure of Course.
type Course struct {
	// @inject_tag: bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	// @inject_tag: bson:"display_order,omitempty"
	DisplayOrder uint64 `protobuf:"varint,4,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	// @inject_tag: validate:"required"
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Visible     bool   `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	// @inject_tag: validate:"required"
	Start *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=start" json:"start,omitempty"`
	// @inject_tag: validate:"required"
	End *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=end" json:"end,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt  *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Categories map[string]string          `protobuf:"bytes,11,rep,name=categories" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Course) GetDisplayOrder() uint64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Course) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Course) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Course) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Course) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Course) GetCategories() map[string]string {
	if m != nil {
		return m.Categories
	}
	return nil
}

// FilterSet contains data for filtering courses.
type FilterSet struct {
	Ids        []string                   `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	TextSearch string                     `protobuf:"bytes,2,opt,name=text_search,json=textSearch" json:"text_search,omitempty"`
	Names      []string                   `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
	Slugs      []string                   `protobuf:"bytes,4,rep,name=slugs" json:"slugs,omitempty"`
	Start      *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=start" json:"start,omitempty"`
	End        *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	Visible    *mysql.BoolField           `protobuf:"bytes,7,opt,name=visible" json:"visible,omitempty"`
}

func (m *FilterSet) Reset()                    { *m = FilterSet{} }
func (m *FilterSet) String() string            { return proto.CompactTextString(m) }
func (*FilterSet) ProtoMessage()               {}
func (*FilterSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FilterSet) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FilterSet) GetTextSearch() string {
	if m != nil {
		return m.TextSearch
	}
	return ""
}

func (m *FilterSet) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *FilterSet) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

func (m *FilterSet) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *FilterSet) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *FilterSet) GetVisible() *mysql.BoolField {
	if m != nil {
		return m.Visible
	}
	return nil
}

// UpsertCoursesRequest contains data when upserts courses.
type UpsertCoursesRequest struct {
	Courses          []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
	UpsertCategories bool      `protobuf:"varint,2,opt,name=upsert_categories,json=upsertCategories" json:"upsert_categories,omitempty"`
}

func (m *UpsertCoursesRequest) Reset()                    { *m = UpsertCoursesRequest{} }
func (m *UpsertCoursesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertCoursesRequest) ProtoMessage()               {}
func (*UpsertCoursesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpsertCoursesRequest) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *UpsertCoursesRequest) GetUpsertCategories() bool {
	if m != nil {
		return m.UpsertCategories
	}
	return false
}

// GetCoursesByFiltersRequest contains fields when querying for courses
// according to filter set.
type GetCoursesByFiltersRequest struct {
	FilterSet  *FilterSet        `protobuf:"bytes,1,opt,name=filter_set,json=filterSet" json:"filter_set,omitempty"`
	Pagination *mysql.Pagination `protobuf:"bytes,8,opt,name=pagination" json:"pagination,omitempty"`
	Sort       *mysql.Sort       `protobuf:"bytes,9,opt,name=sort" json:"sort,omitempty"`
}

func (m *GetCoursesByFiltersRequest) Reset()                    { *m = GetCoursesByFiltersRequest{} }
func (m *GetCoursesByFiltersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCoursesByFiltersRequest) ProtoMessage()               {}
func (*GetCoursesByFiltersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetCoursesByFiltersRequest) GetFilterSet() *FilterSet {
	if m != nil {
		return m.FilterSet
	}
	return nil
}

func (m *GetCoursesByFiltersRequest) GetPagination() *mysql.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetCoursesByFiltersRequest) GetSort() *mysql.Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

// GetCoursesByFiltersResponse contains responses data for courses.
type GetCoursesByFiltersResponse struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
}

func (m *GetCoursesByFiltersResponse) Reset()                    { *m = GetCoursesByFiltersResponse{} }
func (m *GetCoursesByFiltersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCoursesByFiltersResponse) ProtoMessage()               {}
func (*GetCoursesByFiltersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetCoursesByFiltersResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

// DeleteCoursesByFiltersRequest represent request data structure for deleting
// courses by filters.
type DeleteCoursesByFiltersRequest struct {
	FilterSet *FilterSet `protobuf:"bytes,1,opt,name=filter_set,json=filterSet" json:"filter_set,omitempty"`
}

func (m *DeleteCoursesByFiltersRequest) Reset()                    { *m = DeleteCoursesByFiltersRequest{} }
func (m *DeleteCoursesByFiltersRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCoursesByFiltersRequest) ProtoMessage()               {}
func (*DeleteCoursesByFiltersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteCoursesByFiltersRequest) GetFilterSet() *FilterSet {
	if m != nil {
		return m.FilterSet
	}
	return nil
}

// DeleteCoursesByFiltersResponse contains data when courses are deleted.
type DeleteCoursesByFiltersResponse struct {
	Deleted int64 `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteCoursesByFiltersResponse) Reset()                    { *m = DeleteCoursesByFiltersResponse{} }
func (m *DeleteCoursesByFiltersResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCoursesByFiltersResponse) ProtoMessage()               {}
func (*DeleteCoursesByFiltersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteCoursesByFiltersResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*Course)(nil), "courses.Course")
	proto.RegisterType((*FilterSet)(nil), "courses.FilterSet")
	proto.RegisterType((*UpsertCoursesRequest)(nil), "courses.UpsertCoursesRequest")
	proto.RegisterType((*GetCoursesByFiltersRequest)(nil), "courses.GetCoursesByFiltersRequest")
	proto.RegisterType((*GetCoursesByFiltersResponse)(nil), "courses.GetCoursesByFiltersResponse")
	proto.RegisterType((*DeleteCoursesByFiltersRequest)(nil), "courses.DeleteCoursesByFiltersRequest")
	proto.RegisterType((*DeleteCoursesByFiltersResponse)(nil), "courses.DeleteCoursesByFiltersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Courses service

type CoursesClient interface {
	UpsertCourses(ctx context.Context, in *UpsertCoursesRequest, opts ...client.CallOption) (*mysql.UpsertResult, error)
	GetCoursesByFilters(ctx context.Context, in *GetCoursesByFiltersRequest, opts ...client.CallOption) (*GetCoursesByFiltersResponse, error)
	DeleteCoursesByFilters(ctx context.Context, in *DeleteCoursesByFiltersRequest, opts ...client.CallOption) (*DeleteCoursesByFiltersResponse, error)
}

type coursesClient struct {
	c           client.Client
	serviceName string
}

func NewCoursesClient(serviceName string, c client.Client) CoursesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "courses"
	}
	return &coursesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *coursesClient) UpsertCourses(ctx context.Context, in *UpsertCoursesRequest, opts ...client.CallOption) (*mysql.UpsertResult, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.UpsertCourses", in)
	out := new(mysql.UpsertResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetCoursesByFilters(ctx context.Context, in *GetCoursesByFiltersRequest, opts ...client.CallOption) (*GetCoursesByFiltersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.GetCoursesByFilters", in)
	out := new(GetCoursesByFiltersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) DeleteCoursesByFilters(ctx context.Context, in *DeleteCoursesByFiltersRequest, opts ...client.CallOption) (*DeleteCoursesByFiltersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.DeleteCoursesByFilters", in)
	out := new(DeleteCoursesByFiltersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Courses service

type CoursesHandler interface {
	UpsertCourses(context.Context, *UpsertCoursesRequest, *mysql.UpsertResult) error
	GetCoursesByFilters(context.Context, *GetCoursesByFiltersRequest, *GetCoursesByFiltersResponse) error
	DeleteCoursesByFilters(context.Context, *DeleteCoursesByFiltersRequest, *DeleteCoursesByFiltersResponse) error
}

func RegisterCoursesHandler(s server.Server, hdlr CoursesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Courses{hdlr}, opts...))
}

type Courses struct {
	CoursesHandler
}

func (h *Courses) UpsertCourses(ctx context.Context, in *UpsertCoursesRequest, out *mysql.UpsertResult) error {
	return h.CoursesHandler.UpsertCourses(ctx, in, out)
}

func (h *Courses) GetCoursesByFilters(ctx context.Context, in *GetCoursesByFiltersRequest, out *GetCoursesByFiltersResponse) error {
	return h.CoursesHandler.GetCoursesByFilters(ctx, in, out)
}

func (h *Courses) DeleteCoursesByFilters(ctx context.Context, in *DeleteCoursesByFiltersRequest, out *DeleteCoursesByFiltersResponse) error {
	return h.CoursesHandler.DeleteCoursesByFilters(ctx, in, out)
}

func init() { proto.RegisterFile("proto/courses/courses.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x4f, 0xdb, 0x48,
	0x14, 0xc5, 0x71, 0x3e, 0xc8, 0xf5, 0xb2, 0xc0, 0x80, 0x56, 0x23, 0x23, 0x36, 0x91, 0x59, 0xed,
	0x66, 0x3f, 0x70, 0x96, 0xec, 0xcb, 0x16, 0xa9, 0xaa, 0xf8, 0x6c, 0xdf, 0x5a, 0x99, 0xf6, 0x39,
	0x9a, 0xc4, 0x97, 0x30, 0xc5, 0xb1, 0xcd, 0xcc, 0x18, 0x35, 0x3f, 0xa7, 0xea, 0x7f, 0x6c, 0x5f,
	0x2b, 0xcf, 0xd8, 0x26, 0x45, 0x81, 0x14, 0xa9, 0x2f, 0xe0, 0x7b, 0xee, 0x39, 0x77, 0x3c, 0xf7,
	0x1c, 0x07, 0x76, 0x52, 0x91, 0xa8, 0xa4, 0x3f, 0x4e, 0x32, 0x21, 0x51, 0x96, 0xff, 0x7d, 0x8d,
	0x92, 0x56, 0x51, 0xba, 0x9d, 0x49, 0x92, 0x4c, 0x22, 0xec, 0x6b, 0x78, 0x94, 0x5d, 0xf6, 0x15,
	0x9f, 0xa2, 0x54, 0x6c, 0x9a, 0x1a, 0xa6, 0x7b, 0x3a, 0xe1, 0xea, 0x2a, 0x1b, 0xf9, 0xe3, 0x64,
	0xda, 0x7f, 0xcf, 0x59, 0x7c, 0xc5, 0xe2, 0x62, 0xd6, 0xfe, 0x94, 0xc5, 0x6c, 0x82, 0x53, 0x8c,
	0xd5, 0xbe, 0x44, 0x71, 0xcb, 0xc7, 0xc5, 0x98, 0xfe, 0x74, 0x26, 0x6f, 0x22, 0xf3, 0xd7, 0x4c,
	0xf1, 0xbe, 0xd8, 0xd0, 0x3c, 0xd1, 0x2a, 0xf2, 0x33, 0xd4, 0x78, 0x48, 0xad, 0xae, 0xd5, 0x6b,
	0x07, 0x35, 0x1e, 0x12, 0x02, 0xf5, 0x98, 0x4d, 0x91, 0xd6, 0x34, 0xa2, 0x9f, 0x73, 0x4c, 0x46,
	0xd9, 0x84, 0xda, 0x06, 0xcb, 0x9f, 0xc9, 0x1e, 0xac, 0x85, 0x5c, 0xa6, 0x11, 0x9b, 0x0d, 0x13,
	0x11, 0xa2, 0xa0, 0xf5, 0xae, 0xd5, 0xab, 0x07, 0x3f, 0x15, 0xe0, 0xeb, 0x1c, 0x23, 0x5d, 0x70,
	0x42, 0x94, 0x63, 0xc1, 0x53, 0xc5, 0x93, 0x98, 0x36, 0xb4, 0x7e, 0x1e, 0x22, 0x14, 0x5a, 0xb7,
	0x5c, 0xf2, 0x51, 0x84, 0xb4, 0xd9, 0xb5, 0x7a, 0xab, 0x41, 0x59, 0x92, 0x7f, 0xa1, 0x21, 0x15,
	0x13, 0x8a, 0xb6, 0xba, 0x56, 0xcf, 0x19, 0xb8, 0xbe, 0x59, 0x8d, 0x5f, 0xae, 0xc6, 0x7f, 0x5b,
	0xae, 0x26, 0x30, 0x44, 0xf2, 0x0f, 0xd8, 0x18, 0x87, 0x74, 0x75, 0x29, 0x3f, 0xa7, 0x91, 0x67,
	0x00, 0x63, 0x81, 0x4c, 0x61, 0x38, 0x64, 0x8a, 0xb6, 0x97, 0x8a, 0xda, 0x05, 0xfb, 0x48, 0xe5,
	0xd2, 0x2c, 0x0d, 0x4b, 0x29, 0x2c, 0x97, 0x16, 0xec, 0x23, 0x45, 0x5e, 0x00, 0x8c, 0x99, 0xc2,
	0x49, 0x22, 0x38, 0x4a, 0xea, 0x74, 0xed, 0x9e, 0x33, 0xe8, 0xf8, 0x65, 0x1a, 0x8c, 0x27, 0xfe,
	0x49, 0xc5, 0x38, 0x8b, 0x95, 0x98, 0x05, 0x73, 0x12, 0xf7, 0x39, 0xac, 0xdf, 0x6b, 0x93, 0x0d,
	0xb0, 0xaf, 0x71, 0x56, 0x78, 0x98, 0x3f, 0x92, 0x6d, 0x68, 0xdc, 0xb2, 0x28, 0x2b, 0x5d, 0x34,
	0xc5, 0x61, 0xed, 0x7f, 0xcb, 0xfb, 0x6c, 0x41, 0xfb, 0x9c, 0x47, 0x0a, 0xc5, 0x05, 0xaa, 0x5c,
	0xc9, 0x43, 0x49, 0xad, 0xae, 0x9d, 0x2b, 0x79, 0x28, 0x49, 0x07, 0x1c, 0x85, 0x1f, 0xd4, 0x50,
	0x22, 0x13, 0xe3, 0xab, 0x42, 0x0f, 0x39, 0x74, 0xa1, 0x91, 0x7c, 0x74, 0x9e, 0x09, 0x49, 0x6d,
	0x2d, 0x32, 0x45, 0x8e, 0xe6, 0xa9, 0x90, 0xb4, 0x6e, 0x50, 0x5d, 0xdc, 0x59, 0xd8, 0x78, 0xa2,
	0x85, 0xcd, 0xef, 0xb3, 0xf0, 0xaf, 0xbb, 0xf0, 0x98, 0x90, 0x6c, 0xf8, 0x26, 0xe5, 0xc7, 0x49,
	0x12, 0x9d, 0x73, 0x8c, 0xc2, 0x2a, 0x4e, 0x5e, 0x0c, 0xdb, 0xef, 0x52, 0x89, 0x42, 0x99, 0x1d,
	0xcb, 0x00, 0x6f, 0x32, 0x94, 0x8a, 0xfc, 0x09, 0xe5, 0xc7, 0xa7, 0xd7, 0xe0, 0x0c, 0xd6, 0xef,
	0xb9, 0x11, 0x94, 0x7d, 0xf2, 0x37, 0x6c, 0x66, 0x7a, 0xc4, 0x70, 0xce, 0xc2, 0x9a, 0x4e, 0xed,
	0x86, 0x69, 0xdc, 0x39, 0xe3, 0x7d, 0xb2, 0xc0, 0x7d, 0x89, 0xe5, 0x69, 0xc7, 0x33, 0xb3, 0xf4,
	0xea, 0xd8, 0x03, 0x80, 0x4b, 0x8d, 0x0c, 0x25, 0x2a, 0x6d, 0x9d, 0x33, 0x20, 0xd5, 0xc9, 0x95,
	0x43, 0x41, 0xfb, 0xb2, 0x32, 0xeb, 0x00, 0x20, 0x65, 0x13, 0x1e, 0x33, 0xfd, 0x2d, 0x99, 0x94,
	0x6f, 0x16, 0x17, 0x7e, 0x53, 0x35, 0x82, 0x39, 0x12, 0xe9, 0x40, 0x5d, 0x26, 0xa2, 0x4c, 0xb7,
	0x53, 0x90, 0x2f, 0x12, 0xa1, 0x02, 0xdd, 0xf0, 0x5e, 0xc1, 0xce, 0xc2, 0x97, 0x94, 0x69, 0x12,
	0x4b, 0x7c, 0xc2, 0x72, 0xbc, 0x00, 0x76, 0x4f, 0x31, 0x42, 0x85, 0x3f, 0xee, 0xc6, 0xde, 0x21,
	0xfc, 0xfa, 0xd0, 0xcc, 0xe2, 0x05, 0x29, 0xb4, 0x42, 0xcd, 0x30, 0x3f, 0x61, 0x76, 0x50, 0x96,
	0x83, 0x8f, 0x35, 0x68, 0x15, 0x32, 0x72, 0x06, 0x6b, 0xdf, 0x78, 0x4f, 0x76, 0xab, 0x73, 0x17,
	0x65, 0xc2, 0xdd, 0x2a, 0x16, 0x65, 0x9a, 0x01, 0xca, 0x2c, 0x52, 0xde, 0x0a, 0x19, 0xc1, 0xd6,
	0x82, 0x65, 0x91, 0xbd, 0x6a, 0xd8, 0xc3, 0x7e, 0xbb, 0xbf, 0x3d, 0x4e, 0x32, 0xd7, 0xf1, 0x56,
	0xc8, 0x35, 0xfc, 0xb2, 0xf8, 0xca, 0xe4, 0xf7, 0x6a, 0xc2, 0xa3, 0x7b, 0x76, 0xff, 0x58, 0xca,
	0x2b, 0x0f, 0x1b, 0x35, 0xf5, 0x87, 0xf5, 0xdf, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xb1,
	0x8b, 0x8a, 0x9c, 0x06, 0x00, 0x00,
}
