// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course.proto

/*
Package management is a generated protocol buffer package.

It is generated from these files:
	proto/course.proto

It has these top-level messages:
	Course
	Category
	UpsertResult
	BoolField
	UpsertCoursesRequest
	FilterSet
	Pagination
	Sort
	GetCoursesByFiltersRequest
	GetCoursesByFiltersResponse
	CategoryFilterSet
	DeleteCoursesByFiltersRequest
	DeleteCoursesByFiltersResponse
	UpsertCategoriesRequest
*/
package management

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var SortDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Course struct {
	// @inject_tag: bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	// @inject_tag: bson:"display_order,omitempty"
	DisplayOrder uint64 `protobuf:"varint,4,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	// @inject_tag: validate:"required"
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Visible     bool   `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	// @inject_tag: validate:"required"
	Start *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=start" json:"start,omitempty"`
	// @inject_tag: validate:"required"
	End *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=end" json:"end,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt  *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Categories map[string]string          `protobuf:"bytes,11,rep,name=categories" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Course) GetDisplayOrder() uint64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Course) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Course) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Course) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Course) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Course) GetCategories() map[string]string {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Category struct {
	// @inject_tag: bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	// @inject_tag: validate:"required"
	Description  string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	DisplayOrder uint32 `protobuf:"varint,5,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	Visible      bool   `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Courses   map[string]string          `protobuf:"bytes,9,rep,name=courses" json:"courses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetDisplayOrder() uint32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Category) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Category) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Category) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Category) GetCourses() map[string]string {
	if m != nil {
		return m.Courses
	}
	return nil
}

type UpsertResult struct {
	RowsAffected int64 `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected" json:"rows_affected,omitempty"`
	Updated      int64 `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
	Inserted     int64 `protobuf:"varint,3,opt,name=inserted" json:"inserted,omitempty"`
}

func (m *UpsertResult) Reset()                    { *m = UpsertResult{} }
func (m *UpsertResult) String() string            { return proto.CompactTextString(m) }
func (*UpsertResult) ProtoMessage()               {}
func (*UpsertResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpsertResult) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *UpsertResult) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UpsertResult) GetInserted() int64 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

type BoolField struct {
	Value  bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Ignore bool `protobuf:"varint,2,opt,name=ignore" json:"ignore,omitempty"`
}

func (m *BoolField) Reset()                    { *m = BoolField{} }
func (m *BoolField) String() string            { return proto.CompactTextString(m) }
func (*BoolField) ProtoMessage()               {}
func (*BoolField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BoolField) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolField) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

type UpsertCoursesRequest struct {
	Courses          []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
	UpsertCategories bool      `protobuf:"varint,2,opt,name=upsert_categories,json=upsertCategories" json:"upsert_categories,omitempty"`
}

func (m *UpsertCoursesRequest) Reset()                    { *m = UpsertCoursesRequest{} }
func (m *UpsertCoursesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertCoursesRequest) ProtoMessage()               {}
func (*UpsertCoursesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpsertCoursesRequest) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *UpsertCoursesRequest) GetUpsertCategories() bool {
	if m != nil {
		return m.UpsertCategories
	}
	return false
}

type FilterSet struct {
	Ids        []string                   `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	TextSearch string                     `protobuf:"bytes,2,opt,name=text_search,json=textSearch" json:"text_search,omitempty"`
	Names      []string                   `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
	Slugs      []string                   `protobuf:"bytes,4,rep,name=slugs" json:"slugs,omitempty"`
	Start      *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=start" json:"start,omitempty"`
	End        *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=end" json:"end,omitempty"`
	Visible    *BoolField                 `protobuf:"bytes,7,opt,name=visible" json:"visible,omitempty"`
}

func (m *FilterSet) Reset()                    { *m = FilterSet{} }
func (m *FilterSet) String() string            { return proto.CompactTextString(m) }
func (*FilterSet) ProtoMessage()               {}
func (*FilterSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FilterSet) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FilterSet) GetTextSearch() string {
	if m != nil {
		return m.TextSearch
	}
	return ""
}

func (m *FilterSet) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *FilterSet) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

func (m *FilterSet) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *FilterSet) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *FilterSet) GetVisible() *BoolField {
	if m != nil {
		return m.Visible
	}
	return nil
}

type Pagination struct {
	Page    uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PerPage uint64 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Pagination) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type Sort struct {
	Field     string        `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,enum=go.micro.srv.course.management.SortDirection" json:"direction,omitempty"`
}

func (m *Sort) Reset()                    { *m = Sort{} }
func (m *Sort) String() string            { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()               {}
func (*Sort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Sort) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Sort) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASC
}

type GetCoursesByFiltersRequest struct {
	FilterSet  *FilterSet  `protobuf:"bytes,1,opt,name=filter_set,json=filterSet" json:"filter_set,omitempty"`
	Pagination *Pagination `protobuf:"bytes,8,opt,name=pagination" json:"pagination,omitempty"`
	Sort       *Sort       `protobuf:"bytes,9,opt,name=sort" json:"sort,omitempty"`
}

func (m *GetCoursesByFiltersRequest) Reset()                    { *m = GetCoursesByFiltersRequest{} }
func (m *GetCoursesByFiltersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCoursesByFiltersRequest) ProtoMessage()               {}
func (*GetCoursesByFiltersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetCoursesByFiltersRequest) GetFilterSet() *FilterSet {
	if m != nil {
		return m.FilterSet
	}
	return nil
}

func (m *GetCoursesByFiltersRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetCoursesByFiltersRequest) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type GetCoursesByFiltersResponse struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
}

func (m *GetCoursesByFiltersResponse) Reset()                    { *m = GetCoursesByFiltersResponse{} }
func (m *GetCoursesByFiltersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCoursesByFiltersResponse) ProtoMessage()               {}
func (*GetCoursesByFiltersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetCoursesByFiltersResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type CategoryFilterSet struct {
	Ids        []string   `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	TextSearch string     `protobuf:"bytes,2,opt,name=text_search,json=textSearch" json:"text_search,omitempty"`
	Names      []string   `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
	Slugs      []string   `protobuf:"bytes,4,rep,name=slugs" json:"slugs,omitempty"`
	Visible    *BoolField `protobuf:"bytes,5,opt,name=visible" json:"visible,omitempty"`
}

func (m *CategoryFilterSet) Reset()                    { *m = CategoryFilterSet{} }
func (m *CategoryFilterSet) String() string            { return proto.CompactTextString(m) }
func (*CategoryFilterSet) ProtoMessage()               {}
func (*CategoryFilterSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CategoryFilterSet) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *CategoryFilterSet) GetTextSearch() string {
	if m != nil {
		return m.TextSearch
	}
	return ""
}

func (m *CategoryFilterSet) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CategoryFilterSet) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

func (m *CategoryFilterSet) GetVisible() *BoolField {
	if m != nil {
		return m.Visible
	}
	return nil
}

type DeleteCoursesByFiltersRequest struct {
	FilterSet *FilterSet `protobuf:"bytes,1,opt,name=filter_set,json=filterSet" json:"filter_set,omitempty"`
}

func (m *DeleteCoursesByFiltersRequest) Reset()                    { *m = DeleteCoursesByFiltersRequest{} }
func (m *DeleteCoursesByFiltersRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCoursesByFiltersRequest) ProtoMessage()               {}
func (*DeleteCoursesByFiltersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteCoursesByFiltersRequest) GetFilterSet() *FilterSet {
	if m != nil {
		return m.FilterSet
	}
	return nil
}

type DeleteCoursesByFiltersResponse struct {
	Deleted int64 `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteCoursesByFiltersResponse) Reset()                    { *m = DeleteCoursesByFiltersResponse{} }
func (m *DeleteCoursesByFiltersResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCoursesByFiltersResponse) ProtoMessage()               {}
func (*DeleteCoursesByFiltersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteCoursesByFiltersResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type UpsertCategoriesRequest struct {
	Categories    []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
	UpsertCourses bool        `protobuf:"varint,2,opt,name=upsert_courses,json=upsertCourses" json:"upsert_courses,omitempty"`
}

func (m *UpsertCategoriesRequest) Reset()                    { *m = UpsertCategoriesRequest{} }
func (m *UpsertCategoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesRequest) ProtoMessage()               {}
func (*UpsertCategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UpsertCategoriesRequest) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *UpsertCategoriesRequest) GetUpsertCourses() bool {
	if m != nil {
		return m.UpsertCourses
	}
	return false
}

func init() {
	proto.RegisterType((*Course)(nil), "go.micro.srv.course.management.Course")
	proto.RegisterType((*Category)(nil), "go.micro.srv.course.management.Category")
	proto.RegisterType((*UpsertResult)(nil), "go.micro.srv.course.management.UpsertResult")
	proto.RegisterType((*BoolField)(nil), "go.micro.srv.course.management.BoolField")
	proto.RegisterType((*UpsertCoursesRequest)(nil), "go.micro.srv.course.management.UpsertCoursesRequest")
	proto.RegisterType((*FilterSet)(nil), "go.micro.srv.course.management.FilterSet")
	proto.RegisterType((*Pagination)(nil), "go.micro.srv.course.management.Pagination")
	proto.RegisterType((*Sort)(nil), "go.micro.srv.course.management.Sort")
	proto.RegisterType((*GetCoursesByFiltersRequest)(nil), "go.micro.srv.course.management.GetCoursesByFiltersRequest")
	proto.RegisterType((*GetCoursesByFiltersResponse)(nil), "go.micro.srv.course.management.GetCoursesByFiltersResponse")
	proto.RegisterType((*CategoryFilterSet)(nil), "go.micro.srv.course.management.CategoryFilterSet")
	proto.RegisterType((*DeleteCoursesByFiltersRequest)(nil), "go.micro.srv.course.management.DeleteCoursesByFiltersRequest")
	proto.RegisterType((*DeleteCoursesByFiltersResponse)(nil), "go.micro.srv.course.management.DeleteCoursesByFiltersResponse")
	proto.RegisterType((*UpsertCategoriesRequest)(nil), "go.micro.srv.course.management.UpsertCategoriesRequest")
	proto.RegisterEnum("go.micro.srv.course.management.SortDirection", SortDirection_name, SortDirection_value)
}

func init() { proto.RegisterFile("proto/course.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 894 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0xb1, 0x9b, 0xc4, 0x93, 0xb6, 0xb4, 0xcb, 0x09, 0x4c, 0x10, 0x77, 0x91, 0xf9, 0xa3,
	0x70, 0x80, 0x8b, 0x8a, 0x40, 0x77, 0x45, 0x48, 0xb4, 0xe9, 0x1d, 0x08, 0x1e, 0xee, 0xe4, 0x70,
	0x3c, 0xf0, 0x12, 0xb9, 0xf1, 0xc4, 0xac, 0x70, 0xbc, 0x66, 0x77, 0x5d, 0xc8, 0x07, 0xe0, 0x85,
	0x07, 0xf8, 0x16, 0x7c, 0x05, 0xbe, 0x14, 0x1f, 0x02, 0xed, 0x1f, 0x3b, 0xbe, 0x1e, 0x47, 0xd2,
	0x22, 0x78, 0xdb, 0xf9, 0x79, 0x66, 0x76, 0x67, 0x7e, 0xbf, 0x19, 0x03, 0x29, 0x39, 0x93, 0xec,
	0x68, 0xce, 0x2a, 0x2e, 0x30, 0xd2, 0x06, 0xb9, 0x9d, 0xb1, 0x68, 0x49, 0xe7, 0x9c, 0x45, 0x82,
	0x5f, 0x46, 0xf6, 0xd3, 0x32, 0x29, 0x92, 0x0c, 0x97, 0x58, 0xc8, 0xe1, 0x9d, 0x8c, 0xb1, 0x2c,
	0xc7, 0x23, 0xed, 0x7d, 0x51, 0x2d, 0x8e, 0x24, 0x5d, 0xa2, 0x90, 0xc9, 0xb2, 0x34, 0x09, 0xc2,
	0x5f, 0x3d, 0xe8, 0x4e, 0x74, 0x18, 0xd9, 0x87, 0x0e, 0x4d, 0x03, 0x67, 0xe4, 0x8c, 0xfd, 0xb8,
	0x43, 0x53, 0x42, 0xc0, 0x2b, 0x92, 0x25, 0x06, 0x1d, 0x8d, 0xe8, 0xb3, 0xc2, 0x44, 0x5e, 0x65,
	0x81, 0x6b, 0x30, 0x75, 0x26, 0x6f, 0xc0, 0x5e, 0x4a, 0x45, 0x99, 0x27, 0xab, 0x19, 0xe3, 0x29,
	0xf2, 0xc0, 0x1b, 0x39, 0x63, 0x2f, 0xde, 0xb5, 0xe0, 0x23, 0x85, 0x91, 0x11, 0x0c, 0x52, 0x14,
	0x73, 0x4e, 0x4b, 0x49, 0x59, 0x11, 0xec, 0xe8, 0xf8, 0x36, 0x44, 0x02, 0xe8, 0x5d, 0x52, 0x41,
	0x2f, 0x72, 0x0c, 0xba, 0x23, 0x67, 0xdc, 0x8f, 0x6b, 0x93, 0x7c, 0x00, 0x3b, 0x42, 0x26, 0x5c,
	0x06, 0xbd, 0x91, 0x33, 0x1e, 0x1c, 0x0f, 0x23, 0x53, 0x54, 0x54, 0x17, 0x15, 0x7d, 0x5d, 0x17,
	0x15, 0x1b, 0x47, 0xf2, 0x1e, 0xb8, 0x58, 0xa4, 0x41, 0x7f, 0xa3, 0xbf, 0x72, 0x23, 0xf7, 0x01,
	0xe6, 0x1c, 0x13, 0x89, 0xe9, 0x2c, 0x91, 0x81, 0xbf, 0x31, 0xc8, 0xb7, 0xde, 0xa7, 0x52, 0x85,
	0x56, 0x65, 0x5a, 0x87, 0xc2, 0xe6, 0x50, 0xeb, 0x7d, 0x2a, 0xc9, 0x37, 0x00, 0xf3, 0x44, 0x62,
	0xc6, 0x38, 0x45, 0x11, 0x0c, 0x46, 0xee, 0x78, 0x70, 0xfc, 0x71, 0xf4, 0xcf, 0x7c, 0x46, 0x86,
	0xaa, 0x68, 0xd2, 0x04, 0x3e, 0x28, 0x24, 0x5f, 0xc5, 0xad, 0x4c, 0xc3, 0x4f, 0xe1, 0xc5, 0x2b,
	0x9f, 0xc9, 0x01, 0xb8, 0xdf, 0xe3, 0xca, 0x52, 0xab, 0x8e, 0xe4, 0x16, 0xec, 0x5c, 0x26, 0x79,
	0x55, 0x93, 0x6b, 0x8c, 0x93, 0xce, 0x3d, 0x27, 0xfc, 0xdd, 0x85, 0xbe, 0x8d, 0x5f, 0xdd, 0x58,
	0x12, 0x57, 0xd8, 0xf6, 0x9e, 0x65, 0xfb, 0x19, 0xd1, 0x28, 0x45, 0xec, 0x5d, 0x11, 0xcd, 0xf3,
	0x25, 0xf1, 0x34, 0x65, 0xbd, 0x9b, 0x53, 0xd6, 0xbf, 0x0e, 0x65, 0x8f, 0xa0, 0x67, 0x28, 0x11,
	0x81, 0xaf, 0xf9, 0xfa, 0x68, 0x23, 0x5f, 0xb6, 0x93, 0x96, 0x38, 0x4b, 0x57, 0x9d, 0x65, 0x78,
	0x02, 0xbb, 0xed, 0x0f, 0xd7, 0x22, 0x8a, 0xc2, 0xee, 0x93, 0x52, 0x20, 0x97, 0x31, 0x8a, 0x2a,
	0x97, 0xaa, 0xa3, 0x9c, 0xfd, 0x28, 0x66, 0xc9, 0x62, 0x81, 0x73, 0x89, 0x86, 0x36, 0x37, 0xde,
	0x55, 0xe0, 0xa9, 0xc5, 0x54, 0x47, 0x6d, 0x39, 0x3a, 0xa1, 0x1b, 0xd7, 0x26, 0x19, 0x42, 0x9f,
	0x16, 0x2a, 0x1d, 0xa6, 0x9a, 0x4a, 0x37, 0x6e, 0xec, 0xf0, 0x3e, 0xf8, 0x67, 0x8c, 0xe5, 0x0f,
	0x29, 0xe6, 0xe9, 0xfa, 0x45, 0x8e, 0xa6, 0xc4, 0x18, 0xe4, 0x65, 0xe8, 0xd2, 0xac, 0x60, 0xdc,
	0x3c, 0xb4, 0x1f, 0x5b, 0x2b, 0xfc, 0xd9, 0x81, 0x5b, 0xe6, 0x99, 0xb6, 0xd0, 0x18, 0x7f, 0xa8,
	0x50, 0x48, 0xf2, 0xd9, 0xba, 0x97, 0x8e, 0xee, 0xe5, 0xdb, 0xdb, 0x69, 0xbf, 0x69, 0x1e, 0x79,
	0x17, 0x0e, 0x2b, 0x9d, 0x79, 0xd6, 0x9a, 0x23, 0x73, 0xfb, 0x81, 0xf9, 0xb0, 0x9e, 0x83, 0xf0,
	0xb7, 0x0e, 0xf8, 0x0f, 0x69, 0x2e, 0x91, 0x4f, 0x51, 0xaa, 0x3e, 0xd3, 0xd4, 0x5c, 0xec, 0xc7,
	0xea, 0x48, 0xee, 0xc0, 0x40, 0xe2, 0x4f, 0x72, 0x26, 0x30, 0xe1, 0xf3, 0xef, 0x6c, 0xb7, 0x41,
	0x41, 0x53, 0x8d, 0xa8, 0xb2, 0x95, 0xdc, 0x45, 0xe0, 0xea, 0x20, 0x63, 0x28, 0x54, 0x09, 0x5e,
	0x04, 0x9e, 0x41, 0xb5, 0xb1, 0x5e, 0x58, 0x3b, 0xd7, 0x5c, 0x58, 0xdd, 0xed, 0x16, 0xd6, 0x64,
	0x3d, 0x17, 0x46, 0xfa, 0xef, 0x6c, 0xea, 0x5d, 0x43, 0x5f, 0x33, 0x42, 0xe1, 0x27, 0x00, 0x8f,
	0x93, 0x8c, 0x16, 0x89, 0x9e, 0x47, 0x02, 0x5e, 0x99, 0x64, 0x86, 0x54, 0x2f, 0xd6, 0x67, 0xf2,
	0x2a, 0xf4, 0x4b, 0xe4, 0x33, 0x8d, 0x77, 0x34, 0xde, 0x2b, 0x91, 0x3f, 0x4e, 0x32, 0x0c, 0x29,
	0x78, 0x53, 0xc6, 0xa5, 0xaa, 0x7f, 0xa1, 0xd2, 0x5a, 0xc9, 0x1a, 0x83, 0x7c, 0x05, 0x7e, 0x4a,
	0x39, 0xce, 0xf5, 0xf0, 0xab, 0xc8, 0xfd, 0xe3, 0xf7, 0x37, 0xbd, 0x50, 0xa5, 0x3b, 0xaf, 0x83,
	0xe2, 0x75, 0x7c, 0xf8, 0xa7, 0x03, 0xc3, 0xcf, 0xb1, 0x96, 0xcf, 0xd9, 0xca, 0xb0, 0xd8, 0xe8,
	0xe8, 0x0b, 0x80, 0x85, 0x46, 0x66, 0x02, 0xa5, 0x7e, 0xc6, 0x16, 0xed, 0x68, 0x94, 0x10, 0xfb,
	0x8b, 0x46, 0x14, 0x5f, 0x02, 0x94, 0x4d, 0x43, 0xec, 0x62, 0xb8, 0xbb, 0x29, 0xd3, 0xba, 0x85,
	0x71, 0x2b, 0x9a, 0xdc, 0x03, 0x4f, 0x30, 0x5e, 0xff, 0x4c, 0xde, 0xdc, 0xa6, 0xf8, 0x58, 0x47,
	0x84, 0x33, 0x78, 0xed, 0x6f, 0xab, 0x15, 0x25, 0x2b, 0x04, 0xfe, 0xfb, 0xb1, 0x09, 0xff, 0x70,
	0xe0, 0xb0, 0x5e, 0x4b, 0xff, 0xdb, 0x44, 0xb4, 0x14, 0xbb, 0x73, 0x63, 0xc5, 0x52, 0x78, 0xfd,
	0x1c, 0x73, 0x94, 0xf8, 0x9f, 0x6b, 0x21, 0x3c, 0x81, 0xdb, 0xcf, 0xbb, 0xca, 0x12, 0x11, 0x40,
	0x2f, 0xd5, 0x1e, 0xf5, 0xa2, 0xad, 0xcd, 0xf0, 0x17, 0x07, 0x5e, 0x79, 0x72, 0x65, 0xff, 0xb4,
	0x5e, 0xd8, 0x5a, 0x56, 0x86, 0xc1, 0xf1, 0xb6, 0x3f, 0x91, 0xf6, 0x6f, 0x9e, 0xbc, 0x05, 0xfb,
	0xf5, 0xf6, 0xb3, 0x7a, 0x30, 0xab, 0x6f, 0xaf, 0x6a, 0x6f, 0xdb, 0xbb, 0x21, 0xec, 0x3d, 0x35,
	0x59, 0xa4, 0x07, 0xee, 0xe9, 0x74, 0x72, 0xf0, 0x02, 0xe9, 0x83, 0x77, 0xfe, 0x60, 0x3a, 0x39,
	0x70, 0xce, 0x5e, 0xfa, 0xf6, 0xd0, 0xe4, 0x38, 0x5a, 0x5f, 0x7a, 0xd1, 0xd5, 0xcb, 0xe7, 0xc3,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x52, 0x57, 0xb7, 0xc6, 0x76, 0x0a, 0x00, 0x00,
}
