// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/categories.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/categories.proto

It has these top-level messages:
	Category
	CategoryFilterSet
	UpsertCategoriesRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import mysql "github.com/jianhan/course-management-service/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Category struct {
	// @inject_tag: bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" validate:"required"`
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	// @inject_tag: validate:"required"
	Description  string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty" validate:"required"`
	DisplayOrder uint32 `protobuf:"varint,5,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	Visible      bool   `protobuf:"varint,6,opt,name=visible" json:"visible,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
	Courses   map[string]string          `protobuf:"bytes,9,rep,name=courses" json:"courses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto1.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetDisplayOrder() uint32 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Category) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Category) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Category) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Category) GetCourses() map[string]string {
	if m != nil {
		return m.Courses
	}
	return nil
}

type CategoryFilterSet struct {
	Ids        []string         `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	TextSearch string           `protobuf:"bytes,2,opt,name=text_search,json=textSearch" json:"text_search,omitempty"`
	Names      []string         `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
	Slugs      []string         `protobuf:"bytes,4,rep,name=slugs" json:"slugs,omitempty"`
	Visible    *mysql.BoolField `protobuf:"bytes,5,opt,name=visible" json:"visible,omitempty"`
}

func (m *CategoryFilterSet) Reset()                    { *m = CategoryFilterSet{} }
func (m *CategoryFilterSet) String() string            { return proto1.CompactTextString(m) }
func (*CategoryFilterSet) ProtoMessage()               {}
func (*CategoryFilterSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CategoryFilterSet) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *CategoryFilterSet) GetTextSearch() string {
	if m != nil {
		return m.TextSearch
	}
	return ""
}

func (m *CategoryFilterSet) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CategoryFilterSet) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

func (m *CategoryFilterSet) GetVisible() *mysql.BoolField {
	if m != nil {
		return m.Visible
	}
	return nil
}

type UpsertCategoriesRequest struct {
	Categories    []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
	UpsertCourses bool        `protobuf:"varint,2,opt,name=upsert_courses,json=upsertCourses" json:"upsert_courses,omitempty"`
}

func (m *UpsertCategoriesRequest) Reset()                    { *m = UpsertCategoriesRequest{} }
func (m *UpsertCategoriesRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpsertCategoriesRequest) ProtoMessage()               {}
func (*UpsertCategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpsertCategoriesRequest) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *UpsertCategoriesRequest) GetUpsertCourses() bool {
	if m != nil {
		return m.UpsertCourses
	}
	return false
}

func init() {
	proto1.RegisterType((*Category)(nil), "categories.Category")
	proto1.RegisterType((*CategoryFilterSet)(nil), "categories.CategoryFilterSet")
	proto1.RegisterType((*UpsertCategoriesRequest)(nil), "categories.UpsertCategoriesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Categories service

type CategoriesClient interface {
	UpsertCategories(ctx context.Context, in *UpsertCategoriesRequest, opts ...client.CallOption) (*mysql.UpsertResult, error)
}

type categoriesClient struct {
	c           client.Client
	serviceName string
}

func NewCategoriesClient(serviceName string, c client.Client) CategoriesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "categories"
	}
	return &categoriesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *categoriesClient) UpsertCategories(ctx context.Context, in *UpsertCategoriesRequest, opts ...client.CallOption) (*mysql.UpsertResult, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.UpsertCategories", in)
	out := new(mysql.UpsertResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categories service

type CategoriesHandler interface {
	UpsertCategories(context.Context, *UpsertCategoriesRequest, *mysql.UpsertResult) error
}

func RegisterCategoriesHandler(s server.Server, hdlr CategoriesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Categories{hdlr}, opts...))
}

type Categories struct {
	CategoriesHandler
}

func (h *Categories) UpsertCategories(ctx context.Context, in *UpsertCategoriesRequest, out *mysql.UpsertResult) error {
	return h.CategoriesHandler.UpsertCategories(ctx, in, out)
}

func init() { proto1.RegisterFile("proto/categories.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0xb3, 0xae, 0xeb, 0xe9, 0x3a, 0x15, 0x33, 0x81, 0xd5, 0x9b, 0x85, 0x4e, 0x48,
	0x15, 0xd2, 0x12, 0xa9, 0x70, 0x01, 0x43, 0x42, 0xda, 0x2a, 0x76, 0x09, 0x52, 0x06, 0x37, 0x08,
	0xa9, 0x72, 0x93, 0x43, 0x6a, 0x48, 0xe2, 0xcc, 0x76, 0x2a, 0xfa, 0x1a, 0x3c, 0x00, 0xcf, 0x8a,
	0x6c, 0x27, 0x6b, 0x84, 0x40, 0x5c, 0xc5, 0xe7, 0x7f, 0x3e, 0xf3, 0x3b, 0x07, 0x1e, 0x57, 0x52,
	0x68, 0x11, 0x25, 0x4c, 0x63, 0x26, 0x24, 0x47, 0x15, 0x5a, 0x81, 0xc0, 0x5e, 0x99, 0x9e, 0x65,
	0x42, 0x64, 0x39, 0x46, 0xd6, 0xb3, 0xae, 0xbf, 0x46, 0x9a, 0x17, 0xa8, 0x34, 0x2b, 0x2a, 0x17,
	0x3c, 0x7d, 0x9b, 0x71, 0xbd, 0xa9, 0xd7, 0x61, 0x22, 0x8a, 0xe8, 0x1b, 0x67, 0xe5, 0x86, 0x95,
	0x51, 0x22, 0x6a, 0xa9, 0xf0, 0xa2, 0x60, 0x25, 0xcb, 0xb0, 0xc0, 0x52, 0x5f, 0x28, 0x94, 0x5b,
	0x9e, 0x34, 0x65, 0xa2, 0x62, 0xa7, 0xee, 0x72, 0x97, 0x3f, 0xfb, 0xe9, 0xc3, 0xd1, 0xd2, 0xf5,
	0xdb, 0x91, 0x13, 0xe8, 0xf1, 0x94, 0x7a, 0x81, 0x37, 0x1f, 0xc6, 0x3d, 0x9e, 0x12, 0x02, 0x07,
	0x25, 0x2b, 0x90, 0xf6, 0xac, 0x62, 0xdf, 0x46, 0x53, 0x79, 0x9d, 0x51, 0xdf, 0x69, 0xe6, 0x4d,
	0x02, 0x18, 0xa5, 0xa8, 0x12, 0xc9, 0x2b, 0xcd, 0x45, 0x49, 0x0f, 0xac, 0xab, 0x2b, 0x91, 0x73,
	0x18, 0xa7, 0x5c, 0x55, 0x39, 0xdb, 0xad, 0x84, 0x4c, 0x51, 0xd2, 0x7e, 0xe0, 0xcd, 0xc7, 0xf1,
	0x71, 0x23, 0x7e, 0x30, 0x1a, 0xa1, 0x30, 0xd8, 0x72, 0xc5, 0xd7, 0x39, 0xd2, 0xc3, 0xc0, 0x9b,
	0x1f, 0xc5, 0xad, 0x49, 0x5e, 0x03, 0x24, 0x12, 0x99, 0xc6, 0x74, 0xc5, 0x34, 0x1d, 0x04, 0xde,
	0x7c, 0xb4, 0x98, 0x86, 0x8e, 0x4d, 0xd8, 0xb2, 0x09, 0x3f, 0xb6, 0x6c, 0xe2, 0x61, 0x13, 0x7d,
	0xa5, 0x4d, 0x6a, 0x5d, 0xa5, 0x6d, 0xea, 0xd1, 0xff, 0x53, 0x9b, 0xe8, 0x2b, 0x4d, 0xde, 0xc0,
	0xc0, 0xa1, 0x54, 0x74, 0x18, 0xf8, 0xf3, 0xd1, 0xe2, 0x69, 0xd8, 0x59, 0x56, 0x4b, 0x2d, 0x5c,
	0xba, 0x98, 0x77, 0xa5, 0x96, 0xbb, 0xb8, 0xcd, 0x98, 0x5e, 0xc2, 0x71, 0xd7, 0x41, 0x26, 0xe0,
	0x7f, 0xc7, 0x5d, 0x03, 0xd7, 0x3c, 0xc9, 0x29, 0xf4, 0xb7, 0x2c, 0xaf, 0x5b, 0xbc, 0xce, 0xb8,
	0xec, 0xbd, 0xf2, 0x66, 0xbf, 0x3c, 0x78, 0xd8, 0x96, 0xbf, 0xe1, 0xb9, 0x46, 0x79, 0x8b, 0xda,
	0x54, 0xe0, 0xa9, 0xa2, 0x5e, 0xe0, 0x9b, 0x0a, 0x3c, 0x55, 0xe4, 0x0c, 0x46, 0x1a, 0x7f, 0xe8,
	0x95, 0x42, 0x26, 0x93, 0x4d, 0x53, 0x07, 0x8c, 0x74, 0x6b, 0x15, 0xd3, 0xc2, 0x2c, 0x4d, 0x51,
	0xdf, 0x26, 0x39, 0xc3, 0xa8, 0x66, 0x6d, 0x8a, 0x1e, 0x38, 0xd5, 0x1a, 0xe4, 0xf9, 0x9e, 0x7e,
	0xdf, 0x52, 0x9a, 0x84, 0xee, 0x50, 0xae, 0x85, 0xc8, 0x6f, 0x38, 0xe6, 0xe9, 0xfd, 0x3e, 0x66,
	0x5b, 0x78, 0xf2, 0xa9, 0x52, 0x28, 0xf5, 0xf2, 0x9e, 0x47, 0x8c, 0x77, 0x35, 0x2a, 0x4d, 0x5e,
	0x42, 0xe7, 0x7e, 0xed, 0xb0, 0xa3, 0xc5, 0xe9, 0xdf, 0xb8, 0xc5, 0x9d, 0x38, 0xf2, 0x0c, 0x4e,
	0x6a, 0x5b, 0x70, 0xd5, 0x12, 0xef, 0xd9, 0x0b, 0x18, 0x3b, 0xb5, 0x21, 0xb9, 0xf8, 0x02, 0xb0,
	0xef, 0x48, 0xde, 0xc3, 0xe4, 0xcf, 0x29, 0xc8, 0x79, 0xb7, 0xd5, 0x3f, 0x66, 0x9c, 0x3e, 0x6a,
	0xfe, 0xcc, 0xf9, 0x63, 0x54, 0x75, 0xae, 0x67, 0x0f, 0xae, 0x07, 0x9f, 0xfb, 0xee, 0x20, 0x0e,
	0xed, 0xe7, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x12, 0x38, 0x00, 0xa2, 0x03, 0x00,
	0x00,
}
