// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course.proto

/*
Package go_micro_srv_course is a generated protocol buffer package.

It is generated from these files:
	proto/course.proto

It has these top-level messages:
	Course
	AddCourseRequest
	AddCourseResponse
*/
package go_micro_srv_course

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Course struct {
	Id    string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Start *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Course) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

type AddCourseRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AddCourseRequest) Reset()                    { *m = AddCourseRequest{} }
func (m *AddCourseRequest) String() string            { return proto.CompactTextString(m) }
func (*AddCourseRequest) ProtoMessage()               {}
func (*AddCourseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddCourseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddCourseResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *AddCourseResponse) Reset()                    { *m = AddCourseResponse{} }
func (m *AddCourseResponse) String() string            { return proto.CompactTextString(m) }
func (*AddCourseResponse) ProtoMessage()               {}
func (*AddCourseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddCourseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Course)(nil), "go.micro.srv.course.Course")
	proto.RegisterType((*AddCourseRequest)(nil), "go.micro.srv.course.AddCourseRequest")
	proto.RegisterType((*AddCourseResponse)(nil), "go.micro.srv.course.AddCourseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CourseManager service

type CourseManagerClient interface {
	Add(ctx context.Context, in *AddCourseRequest, opts ...client.CallOption) (*AddCourseResponse, error)
}

type courseManagerClient struct {
	c           client.Client
	serviceName string
}

func NewCourseManagerClient(serviceName string, c client.Client) CourseManagerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.course"
	}
	return &courseManagerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *courseManagerClient) Add(ctx context.Context, in *AddCourseRequest, opts ...client.CallOption) (*AddCourseResponse, error) {
	req := c.c.NewRequest(c.serviceName, "CourseManager.Add", in)
	out := new(AddCourseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CourseManager service

type CourseManagerHandler interface {
	Add(context.Context, *AddCourseRequest, *AddCourseResponse) error
}

func RegisterCourseManagerHandler(s server.Server, hdlr CourseManagerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CourseManager{hdlr}, opts...))
}

type CourseManager struct {
	CourseManagerHandler
}

func (h *CourseManager) Add(ctx context.Context, in *AddCourseRequest, out *AddCourseResponse) error {
	return h.CourseManagerHandler.Add(ctx, in, out)
}

func init() { proto.RegisterFile("proto/course.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x60, 0xb3, 0x5b, 0x0b, 0x8e, 0x28, 0x75, 0xbc, 0x2c, 0x7b, 0xb1, 0x2c, 0xb4, 0xf4,
	0x20, 0xb3, 0x52, 0x9f, 0xa0, 0x78, 0xf6, 0xb2, 0x88, 0xf7, 0xb4, 0x19, 0xc3, 0x82, 0x49, 0xd6,
	0x24, 0xeb, 0x53, 0xf8, 0xd0, 0xd2, 0xc4, 0xaa, 0x88, 0xd0, 0xdb, 0x24, 0xf9, 0x32, 0xf3, 0x27,
	0x80, 0x83, 0x77, 0xd1, 0xb5, 0x3b, 0x37, 0xfa, 0xc0, 0x94, 0x16, 0x78, 0xad, 0x1d, 0x99, 0x7e,
	0xe7, 0x1d, 0x05, 0xff, 0x4e, 0xf9, 0xa8, 0xbe, 0xd1, 0xce, 0xe9, 0x57, 0x6e, 0x13, 0xd9, 0x8e,
	0x2f, 0x6d, 0xec, 0x0d, 0x87, 0x28, 0xcd, 0x90, 0x6f, 0x35, 0x1f, 0x02, 0xa6, 0x0f, 0xc9, 0xe2,
	0x25, 0x14, 0xbd, 0xaa, 0xc4, 0x5c, 0xac, 0xce, 0xba, 0xa2, 0x57, 0x88, 0x30, 0xb1, 0xd2, 0x70,
	0x55, 0xa4, 0x9d, 0x54, 0xe3, 0x1d, 0x9c, 0x86, 0x28, 0x7d, 0xac, 0xca, 0xb9, 0x58, 0x9d, 0xaf,
	0x6b, 0xca, 0xfd, 0xe9, 0xd0, 0x9f, 0x9e, 0x0e, 0xfd, 0xbb, 0x0c, 0xf1, 0x16, 0x4a, 0xb6, 0xaa,
	0x9a, 0x1c, 0xf5, 0x7b, 0xd6, 0x2c, 0x61, 0xb6, 0x51, 0x2a, 0x07, 0xea, 0xf8, 0x6d, 0xe4, 0x10,
	0xbf, 0x73, 0x88, 0x9f, 0x1c, 0xcd, 0x02, 0xae, 0x7e, 0xb9, 0x30, 0x38, 0x1b, 0x18, 0x67, 0x50,
	0x9a, 0xa0, 0xbf, 0xdc, 0xbe, 0x5c, 0x6b, 0xb8, 0xc8, 0xe6, 0x51, 0x5a, 0xa9, 0xd9, 0xe3, 0x33,
	0x94, 0x1b, 0xa5, 0x70, 0x41, 0xff, 0x7c, 0x16, 0xfd, 0x9d, 0x5c, 0x2f, 0x8f, 0xb1, 0x3c, 0xb8,
	0x39, 0xd9, 0x4e, 0xd3, 0x83, 0xee, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x26, 0x16, 0xe2, 0xe3,
	0x99, 0x01, 0x00, 0x00,
}
