// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mysql.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/mysql.proto

It has these top-level messages:
	UpsertResult
	BoolField
	Pagination
	Sort
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var SortDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortDirection) String() string {
	return proto1.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpsertResult struct {
	RowsAffected int64 `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected" json:"rows_affected,omitempty"`
	Updated      int64 `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
	Inserted     int64 `protobuf:"varint,3,opt,name=inserted" json:"inserted,omitempty"`
}

func (m *UpsertResult) Reset()                    { *m = UpsertResult{} }
func (m *UpsertResult) String() string            { return proto1.CompactTextString(m) }
func (*UpsertResult) ProtoMessage()               {}
func (*UpsertResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertResult) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *UpsertResult) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UpsertResult) GetInserted() int64 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

type BoolField struct {
	Value  bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Ignore bool `protobuf:"varint,2,opt,name=ignore" json:"ignore,omitempty"`
}

func (m *BoolField) Reset()                    { *m = BoolField{} }
func (m *BoolField) String() string            { return proto1.CompactTextString(m) }
func (*BoolField) ProtoMessage()               {}
func (*BoolField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BoolField) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolField) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

type Pagination struct {
	Page    uint64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PerPage uint64 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto1.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pagination) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type Sort struct {
	Field     string        `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,enum=go.micro.srv.mysql.SortDirection" json:"direction,omitempty"`
}

func (m *Sort) Reset()                    { *m = Sort{} }
func (m *Sort) String() string            { return proto1.CompactTextString(m) }
func (*Sort) ProtoMessage()               {}
func (*Sort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Sort) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Sort) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASC
}

func init() {
	proto1.RegisterType((*UpsertResult)(nil), "go.micro.srv.mysql.UpsertResult")
	proto1.RegisterType((*BoolField)(nil), "go.micro.srv.mysql.BoolField")
	proto1.RegisterType((*Pagination)(nil), "go.micro.srv.mysql.Pagination")
	proto1.RegisterType((*Sort)(nil), "go.micro.srv.mysql.Sort")
	proto1.RegisterEnum("go.micro.srv.mysql.SortDirection", SortDirection_name, SortDirection_value)
}

func init() { proto1.RegisterFile("proto/mysql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x6d, 0xbb, 0xed, 0x6e, 0x87, 0x56, 0xea, 0x20, 0x52, 0x3d, 0xe9, 0x7a, 0x11, 0x0f,
	0x11, 0xf4, 0x24, 0x1e, 0xa4, 0x7f, 0xf4, 0x5c, 0x52, 0xbc, 0x08, 0x52, 0x62, 0x77, 0xba, 0x04,
	0xb6, 0x9b, 0x98, 0x4d, 0x2b, 0x7e, 0x7b, 0xc9, 0x6c, 0xab, 0x88, 0xa7, 0xcc, 0x7b, 0x2f, 0xef,
	0x37, 0x90, 0xc0, 0x91, 0x75, 0xc6, 0x9b, 0x9b, 0xf5, 0x57, 0xf5, 0x51, 0x08, 0x9e, 0x11, 0x73,
	0x23, 0xd6, 0x7a, 0xe9, 0x8c, 0xa8, 0xdc, 0x56, 0x70, 0x92, 0x6a, 0xe8, 0xbd, 0xd8, 0x8a, 0x9c,
	0x97, 0x54, 0x6d, 0x0a, 0x8f, 0x97, 0xd0, 0x77, 0xe6, 0xb3, 0x5a, 0xa8, 0xd5, 0x8a, 0x96, 0x9e,
	0xb2, 0x61, 0xe3, 0xbc, 0x71, 0xd5, 0x92, 0xbd, 0x60, 0x8e, 0x76, 0x1e, 0x0e, 0x21, 0xde, 0xd8,
	0x4c, 0x85, 0xb8, 0xc9, 0xf1, 0x5e, 0xe2, 0x19, 0x24, 0xba, 0x0c, 0x38, 0xca, 0x86, 0x2d, 0x8e,
	0x7e, 0x74, 0x7a, 0x0f, 0xdd, 0xb1, 0x31, 0xc5, 0xb3, 0xa6, 0x22, 0xc3, 0x63, 0x68, 0x6f, 0x55,
	0xb1, 0x21, 0xe6, 0x27, 0xb2, 0x16, 0x78, 0x02, 0x1d, 0x9d, 0x97, 0xc6, 0x11, 0x73, 0x13, 0xb9,
	0x53, 0xe9, 0x03, 0xc0, 0x4c, 0xe5, 0xba, 0x54, 0x5e, 0x9b, 0x12, 0x11, 0x22, 0xab, 0xf2, 0xba,
	0x1a, 0x49, 0x9e, 0xf1, 0x14, 0x12, 0x4b, 0x6e, 0xc1, 0x7e, 0x93, 0xfd, 0xd8, 0x92, 0x9b, 0xa9,
	0x9c, 0xd2, 0x37, 0x88, 0xe6, 0xc6, 0xf9, 0xb0, 0x72, 0x15, 0x76, 0x73, 0xaf, 0x2b, 0x6b, 0x81,
	0x8f, 0xd0, 0xcd, 0xb4, 0xa3, 0x65, 0x20, 0x73, 0xf3, 0xf0, 0xf6, 0x42, 0xfc, 0x7f, 0x28, 0x11,
	0x10, 0xd3, 0xfd, 0x45, 0xf9, 0xdb, 0xb9, 0x4e, 0xa1, 0xff, 0x27, 0xc3, 0x18, 0x5a, 0xa3, 0xf9,
	0x64, 0x70, 0x80, 0x09, 0x44, 0xd3, 0xa7, 0xf9, 0x64, 0xd0, 0x18, 0xc7, 0xaf, 0x6d, 0xfe, 0x82,
	0xf7, 0x0e, 0x1f, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x4a, 0x60, 0xb1, 0x9e, 0x01,
	0x00, 0x00,
}
