-- MySQL Script generated by MySQL Workbench
-- Sat 03 Feb 2018 10:49:53 AEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `slug` VARCHAR(512) NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `description` TEXT NOT NULL,
  `visible` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  FULLTEXT INDEX `description_FULLTEXT` (`description` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = dec8;


-- -----------------------------------------------------
-- Table `mydb`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prices` (
  `id` CHAR(36) NOT NULL,
  `type` VARCHAR(128) NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `value` DECIMAL(19,2) NOT NULL,
  `visible` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `description` VARCHAR(1024) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `course_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_prices_course_INDEX` (`course_id` ASC),
  INDEX `type_INDEX` (`type` ASC),
  INDEX `visible_INDEX` (`visible` ASC),
  INDEX `value_INDEX` USING BTREE (`value` ASC),
  FULLTEXT INDEX `description_FULLTEXT` USING BTREE (`description` ASC),
  CONSTRAINT `fk_prices_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `categoriescol` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  FULLTEXT INDEX `description_FULLTEXT` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses_categories` (
  `courses_id` CHAR(36) NOT NULL,
  `categories_id` CHAR(36) NOT NULL,
  `display_order` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `categories_id`),
  INDEX `fk_courses_has_categories_categories1_idx` (`categories_id` ASC),
  INDEX `fk_courses_has_categories_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_courses_has_categories_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = dec8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
